name: Singularity build
description: Build singularity container from local docker
inputs:
  input:
    description: "input source e.g. docker://centos"
    required: true
  output:
    description: "output image e.g. centos.sif"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - build
    - ${{ inputs.output }}
    - ${{ inputs.input }}
