name: Rescale upload
description: upload a file to rescale
inputs:
  rescale_token:
    description: Rescale API key
    required: true
  rescale_platform: Rescale platform
    decription: Rescale platform address
    required: false
    default: platform.rescale.com
  filename:
    description: File to upload
    required: true
runs:
  using: 'docker'
  image: Dockerfile
  args:
    - ${{ inputs.filename }}
